// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQfxJP-YPhz7NRxmNszuoa9o-XJZz7Gc',
    appId: '1:100805144180:web:17d435f0acc3173fa8ab21',
    messagingSenderId: '100805144180',
    projectId: 'minimal-app-3dc26',
    authDomain: 'minimal-app-3dc26.firebaseapp.com',
    storageBucket: 'minimal-app-3dc26.appspot.com',
    measurementId: 'G-T54307KNTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnEhL3WAML_2YTSLHyojC0kUKqjE81PYY',
    appId: '1:100805144180:android:aaf5712226e8cb94a8ab21',
    messagingSenderId: '100805144180',
    projectId: 'minimal-app-3dc26',
    storageBucket: 'minimal-app-3dc26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndReTLlU42HDWnN9V9xZDzqtZOO4ciFs',
    appId: '1:100805144180:ios:433b0f39f186eb2ea8ab21',
    messagingSenderId: '100805144180',
    projectId: 'minimal-app-3dc26',
    storageBucket: 'minimal-app-3dc26.appspot.com',
    iosBundleId: 'com.example.minimalFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndReTLlU42HDWnN9V9xZDzqtZOO4ciFs',
    appId: '1:100805144180:ios:30778a6a8c4b987ea8ab21',
    messagingSenderId: '100805144180',
    projectId: 'minimal-app-3dc26',
    storageBucket: 'minimal-app-3dc26.appspot.com',
    iosBundleId: 'com.example.minimalFirebase.RunnerTests',
  );
}
